"use client";

import React from "react";
import {
  Utensils,
  Car,
  Smartphone,
  Zap,
  Home,
  Shirt,
  Heart,
  Gamepad2,
  BookOpen,
  Wallet,
  Briefcase,
  TrendingUp,
  ArrowLeftRight,
  ShoppingBag,
  Plane,
  RefreshCw,
  Gift,
  BarChart2,
  Users,
  Tag,
  Landmark,
  Coins,
  CreditCard,
  Target,
  Laptop,
  GraduationCap,
  Gem,
  Dumbbell,
  Globe,
  ClipboardList,
  AlertTriangle,
  CheckCircle2,
  CircleDot,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  // Category IDs & icon keys
  food_dining: Utensils,
  utensils: Utensils,
  food: Utensils,
  restaurant: Utensils,
  transport: Car,
  car: Car,
  vehicle: Car,
  airtime_data: Smartphone,
  phone: Smartphone,
  smartphone: Smartphone,
  mobile: Smartphone,
  utilities: Zap,
  zap: Zap,
  electricity: Zap,
  lightbulb: Zap,
  rent_housing: Home,
  housing: Home,
  home: Home,
  house: Home,
  clothing: Shirt,
  shirt: Shirt,
  clothes: Shirt,
  health: Heart,
  heart: Heart,
  medical: Heart,
  entertainment: Gamepad2,
  gamepad: Gamepad2,
  gaming: Gamepad2,
  education: BookOpen,
  book: BookOpen,
  books: BookOpen,
  savings: Wallet,
  wallet: Wallet,
  salary: Briefcase,
  briefcase: Briefcase,
  business: TrendingUp,
  "trending-up": TrendingUp,
  transfer: ArrowLeftRight,
  "arrow-left-right": ArrowLeftRight,
  shopping: ShoppingBag,
  "shopping-bag": ShoppingBag,
  travel: Plane,
  plane: Plane,
  subscriptions: RefreshCw,
  "refresh-cw": RefreshCw,
  refresh: RefreshCw,
  gifts: Gift,
  gift: Gift,
  investment: TrendingUp,
  investment_in: BarChart2,
  chart: BarChart2,
  "bar-chart": BarChart2,
  family: Users,
  users: Users,
  other: Tag,
  tag: Tag,
  pin: Tag,

  // Account types
  bank: Landmark,
  cash: Coins,
  coins: Coins,
  credit: CreditCard,
  card: CreditCard,

  // Goal types
  target: Target,
  goal: Target,
  laptop: Laptop,
  pc: Laptop,
  tech: Laptop,
  grad: GraduationCap,
  degree: GraduationCap,
  ring: Gem,
  gem: Gem,
  gym: Dumbbell,
  fitness: Dumbbell,
  dumbbell: Dumbbell,
  world: Globe,
  globe: Globe,

  // Unicode Emojis mapped to standard Lucide icons (stored with unicode escapes)
  "\u{1F37D}\u{FE0F}": Utensils,
  "\u{1F37D}": Utensils,
  "\u{1F697}": Car,
  "\u{1F4F1}": Smartphone,
  "\u{1F4A1}": Zap,
  "\u{1F3E0}": Home,
  "\u{1F455}": Shirt,
  "\u{2764}\u{FE0F}": Heart,
  "\u{2764}": Heart,
  "\u{1F3AE}": Gamepad2,
  "\u{1F4DA}": BookOpen,
  "\u{1F4B0}": Wallet,
  "\u{1F4B8}": Wallet,
  "\u{1F4BC}": Briefcase,
  "\u{1F4C8}": TrendingUp,
  "\u{2194}\u{FE0F}": ArrowLeftRight,
  "\u{2194}": ArrowLeftRight,
  "\u{1F6CD}\u{FE0F}": ShoppingBag,
  "\u{1F6CD}": ShoppingBag,
  "\u{2708}\u{FE0F}": Plane,
  "\u{2708}": Plane,
  "\u{1F504}": RefreshCw,
  "\u{1F381}": Gift,
  "\u{1F4CA}": BarChart2,
  "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}": Users,
  "\u{1F4CC}": Tag,
  "\u{1F3E6}": Landmark,
  "\u{1F4B5}": Coins,
  "\u{1F4B3}": CreditCard,
  "\u{1F3AF}": Target,
  "\u{1F4BB}": Laptop,
  "\u{1F393}": GraduationCap,
  "\u{1F48D}": Gem,
  "\u{1F3CB}\u{FE0F}": Dumbbell,
  "\u{1F3CB}": Dumbbell,
  "\u{1F30D}": Globe,
  "\u{1F4CB}": ClipboardList,
  "\u{1F6A8}": AlertTriangle,
  "\u{1F631}": AlertTriangle,
  "\u{26A0}\u{FE0F}": AlertTriangle,
  "\u{26A0}": AlertTriangle,
  "\u{2705}": CheckCircle2,
};

interface FlowiseIconProps {
  icon?: string | null;
  className?: string;
  size?: number;
  style?: React.CSSProperties;
}

export function FlowiseIcon({
  icon,
  className = "w-4 h-4",
  size,
  style,
}: FlowiseIconProps): React.ReactElement {
  if (!icon) {
    return <CircleDot className={className} size={size} style={style} />;
  }

  const cleanKey = icon.trim().toLowerCase();
  const IconComponent = ICON_MAP[icon] ?? ICON_MAP[cleanKey] ?? CircleDot;

  return <IconComponent className={className} size={size} style={style} />;
}
