-- ============================================================
-- French Daily Challenge PWA — Database schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- ── 1. Push subscriptions (one row = your phone's push endpoint) ─────────────
create table if not exists french_subscriptions (
  id         uuid primary key default gen_random_uuid(),
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  created_at timestamptz not null default now()
);

alter table french_subscriptions enable row level security;
-- Only the service-role key (server) can read/write subscriptions
create policy "service-role only" on french_subscriptions
  using (false);

-- ── 2. Daily challenges (generated by LLM via GitHub Action) ─────────────────
create table if not exists french_challenges (
  id           uuid primary key default gen_random_uuid(),
  challenge_date date not null unique,
  type         text not null check (type in ('speaking', 'writing', 'reading')),
  prompt_text  text not null,
  example_text text,          -- the sentence / passage to use
  created_at   timestamptz not null default now()
);

create index if not exists french_challenges_date_idx on french_challenges(challenge_date);

alter table french_challenges enable row level security;

-- Anyone (anon) can read today's challenge from the client
create policy "anon read challenges" on french_challenges
  for select using (true);

-- ── 3. Completion logs (one row per completed challenge) ──────────────────────
create table if not exists french_logs (
  id           uuid primary key default gen_random_uuid(),
  challenge_id uuid references french_challenges(id) on delete cascade,
  type         text not null check (type in ('speaking', 'writing', 'reading')),
  proof_text   text,          -- for writing challenges
  proof_url    text,          -- for audio uploads (Supabase Storage URL)
  created_at   timestamptz not null default now()
);

create index if not exists french_logs_created_at_idx on french_logs(created_at desc);

alter table french_logs enable row level security;

-- Anon can insert and read their own logs
create policy "anon insert logs" on french_logs
  for insert with check (true);

create policy "anon read logs" on french_logs
  for select using (true);

-- ── 4. Streak tracker (single row, upserted on each completion) ──────────────
create table if not exists french_streaks (
  id                  int primary key default 1 check (id = 1),  -- singleton
  current_streak      int not null default 0,
  longest_streak      int not null default 0,
  last_completed_date date,
  total_completions   int not null default 0,
  updated_at          timestamptz not null default now()
);

alter table french_streaks enable row level security;

create policy "anon read streak" on french_streaks
  for select using (true);

create policy "anon update streak" on french_streaks
  for update using (true);

-- Insert the singleton row
insert into french_streaks (id) values (1) on conflict do nothing;

-- ── 5. Vocabulary log (words and sentences learned) ──────────────────────────
create table if not exists french_vocabulary (
  id              uuid primary key default gen_random_uuid(),
  entry_type      text not null check (entry_type in ('word', 'sentence')),
  french_text     text not null,
  english_meaning text not null,
  notes           text,          -- optional extra context
  created_at      timestamptz not null default now()
);

create index if not exists french_vocabulary_created_at_idx on french_vocabulary(created_at desc);

alter table french_vocabulary enable row level security;

create policy "anon insert vocab" on french_vocabulary
  for insert with check (true);

create policy "anon read vocab" on french_vocabulary
  for select using (true);

create policy "anon delete vocab" on french_vocabulary
  for delete using (true);

-- ── 6. Supabase Storage bucket for audio recordings ──────────────────────────
insert into storage.buckets (id, name, public)
values ('french-audio', 'french-audio', true)
on conflict (id) do nothing;

-- Guard storage policies against duplicate errors (other tools may have run first)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename  = 'objects'
      and policyname = 'french anon upload audio'
  ) then
    execute $p$
      create policy "french anon upload audio" on storage.objects
        for insert with check (bucket_id = 'french-audio')
    $p$;
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename  = 'objects'
      and policyname = 'french anon read audio'
  ) then
    execute $p$
      create policy "french anon read audio" on storage.objects
        for select using (bucket_id = 'french-audio')
    $p$;
  end if;
end
$$;

