-- ============================================================
-- Frontend track, take 3: fixes both the double-escaping bug in
-- take 2 AND 3 pre-existing quad-quote bugs in the original source
-- (TkDodo's / Drei's, old day 40/70/75) that survived take 2's
-- decode. Re-synced to rust_challenge_rewrite_day9_v2.sql's day
-- 9-188 numbering. Run the v2 backend file first, then this.
--
-- Content fixes: Framer Motion -> Motion rename; WASM days
-- rescoped to verification-only (proof generation stays server-
-- side); Server Actions / TS discriminated unions+satisfies / a
-- feature-flag day / an i18n touch added; 3 new days inserted at
-- the same points the backend inserted days (privacy-conscious-UI
-- week, a network-resilience day, a proving-queue UI day); the
-- 7x-identical bonus-day filler replaced with real, distinct tasks.
--
-- Flagged, not changed: the WebGL/shaders block (14 days) is a
-- portfolio differentiator, not universal senior-frontend bar —
-- cut that first if you fall behind schedule.
-- ============================================================

ALTER TABLE rust_challenge_days ADD COLUMN IF NOT EXISTS frontend_task text;

UPDATE rust_challenge_days SET frontend_task = 'Design Eye: Analyze the typography scale of Stripe.com using DevTools. Recreate their exact font sizes and line-heights in a codepen. *(Resource: Refactoring UI Chapter on Typography)*' WHERE day_number = 8;
UPDATE rust_challenge_days SET frontend_task = 'Design Eye: Read Josh W. Comeau''s article ''Designing Beautiful Shadows in CSS''. Implement a multi-layered soft shadow. *(Resource: [Josh W Comeau Shadows](https://www.joshwcomeau.com/css/designing-shadows/))*' WHERE day_number = 9;
UPDATE rust_challenge_days SET frontend_task = 'Layouts: Deep dive into CSS Grid. Build a complex bento-box layout using CSS Grid without media queries (using minmax). *(Resource: [Kevin Powell Grid](https://www.youtube.com/watch?v=rg7Fvvl3taU))*' WHERE day_number = 10;
UPDATE rust_challenge_days SET frontend_task = 'Spacing: Implement an 8pt spacing system using CSS Custom Properties (variables). Build a card component strictly adhering to these tokens. *(Resource: Refactoring UI Chapter on Layout/Spacing)*' WHERE day_number = 11;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Create a fluid typography scale using `clamp()` so font sizes scale perfectly from mobile to desktop. *(Resource: [Utopia Fluid Typography](https://utopia.fyi/))*' WHERE day_number = 12;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Build a custom, styled range slider input. Style the thumb and track across different browsers. *(Resource: [CSS Tricks styling range inputs](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/))*' WHERE day_number = 13;
UPDATE rust_challenge_days SET frontend_task = 'Review: Audit the bento-box layout in Lighthouse. Ensure it''s 100% accessible (aria-labels, keyboard focus states).' WHERE day_number = 14;
UPDATE rust_challenge_days SET frontend_task = 'Color: Study HSL and LCH color spaces. Create a harmonious 9-step color palette in CSS using HSL manipulations. *(Resource: [Josh W Comeau Color Spaces](https://www.joshwcomeau.com/css/color-formats/))*' WHERE day_number = 15;
UPDATE rust_challenge_days SET frontend_task = 'Modern CSS: Learn CSS `color-mix()` and relative colors. Create a dynamic button hover state that automatically darkens the base color. *(Resource: [Adam Argyle on CSS color](https://developer.chrome.com/articles/css-color-mix/))*' WHERE day_number = 16;
UPDATE rust_challenge_days SET frontend_task = 'Modern CSS: Implement a dark mode toggle purely in CSS using `color-scheme` and CSS variables, mapping the 9-step palette for dark context. *(Resource: [web.dev Dark Mode](https://web.dev/articles/color-scheme))*' WHERE day_number = 17;
UPDATE rust_challenge_days SET frontend_task = 'Modern CSS: Deep dive into the `:has()` pseudo-class. Build a parent card that changes style when a child checkbox is checked. *(Resource: [Kevin Powell :has() tutorial](https://www.youtube.com/watch?v=tTzMNyHOIjc))*' WHERE day_number = 18;
UPDATE rust_challenge_days SET frontend_task = 'Modern CSS: Learn CSS Container Queries (`@container`). Make a component change its internal layout based on its container width, not viewport width. *(Resource: [MDN Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries))*' WHERE day_number = 19;
UPDATE rust_challenge_days SET frontend_task = 'Modern CSS: Build a complex masonry layout using modern CSS Grid and `:nth-child()` math. *(Resource: [Smashing Magazine Masonry](https://www.smashingmagazine.com/2023/01/css-masonry-layout/))*' WHERE day_number = 20;
UPDATE rust_challenge_days SET frontend_task = 'Review: Take a screenshot of the dark mode UI and run it through a color contrast checker (e.g., Coolors contrast checker) to ensure WCAG AA compliance.' WHERE day_number = 21;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Intro to Motion (the library formerly branded Framer Motion — same team, same API, renamed in late 2024). Build a basic mount/unmount animation for a modal component using `<AnimatePresence>`. *(Resource: [Motion Docs](https://motion.dev/docs/react-animate-presence))*' WHERE day_number = 22;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Master `layoutId` in Motion. Build a magic underline navigation menu where the active pill slides between tabs smoothly. *(Resource: [Emil Kowalski Animations on Twitter/X](https://twitter.com/emilkowalski_))*' WHERE day_number = 23;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Learn about spring physics vs easing curves. Build a button that has a satisfying ''boop'' scale effect on hover and tap. *(Resource: [Josh W. Comeau on Animation](https://www.joshwcomeau.com/animation/css-transitions/))*' WHERE day_number = 24;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Create a staggered list animation where items cascade in on page load. *(Resource: [Motion Orchestration](https://motion.dev/docs/animation/#orchestration))*' WHERE day_number = 25;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Build an accordion component that animates its height smoothly from 0 to ''auto''. *(Resource: [Build UI Motion course](https://buildui.com/courses/framer-motion-recipes))*' WHERE day_number = 26;
UPDATE rust_challenge_days SET frontend_task = 'Motion: Implement a drag-to-reorder list using `<Reorder.Group>` in Motion. *(Resource: [Motion Reorder](https://motion.dev/docs/reorder/))*' WHERE day_number = 27;
UPDATE rust_challenge_days SET frontend_task = 'Review: Audit the animations to ensure they respect `prefers-reduced-motion` using the `useReducedMotion` hook.' WHERE day_number = 28;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Implement the CSS View Transitions API for a seamless multi-page (or multi-state) transition in a vanilla app. *(Resource: [Chrome DevTools View Transitions](https://developer.chrome.com/docs/web-platform/view-transitions/))*' WHERE day_number = 29;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Create a magnetic cursor effect for a button (button subtly pulls towards the cursor when hovering nearby). *(Resource: [Codrops Magnetic Button](https://tympanus.net/codrops/))*' WHERE day_number = 30;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Build a custom scroll progress indicator using Motion `useScroll`. *(Resource: [Motion Scroll](https://motion.dev/docs/use-scroll/))*' WHERE day_number = 31;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Implement a parallax scroll effect for images within a blog post layout. *(Resource: [Olivier Larose WebGL/Parallax YouTube channel](https://www.youtube.com/@olivierlarose1))*' WHERE day_number = 32;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Recreate the Apple-style ''scroll-driven video sequence'' (scrubbing a video on scroll). *(Resource: [Jhey Tompkins Scroll-driven animations](https://jhey.dev/))*' WHERE day_number = 33;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Create a smooth, glassmorphism context menu that appears at the exact cursor coordinates on right-click. *(Resource: [UI.dev React Context Menu](https://ui.dev/))*' WHERE day_number = 34;
UPDATE rust_challenge_days SET frontend_task = 'Review: Record a video of the scroll animations and review them frame-by-frame. Are there janks? Optimize the transform/opacity layers.' WHERE day_number = 35;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Deep dive into React Server Components (RSC) mental model. Understand the network boundary. *(Resource: [Dan Abramov on RSCs](https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md))*' WHERE day_number = 36;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Build a Next.js App Router layout with nested Suspense boundaries to demonstrate streaming HTML. *(Resource: [Next.js Streaming docs](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming))*' WHERE day_number = 37;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Replace traditional `useEffect` data fetching with React Server Components fetching (promises passed to the client) for reads, and Server Actions for mutations — the senior-level bar in 2026 expects fluency in both, not just RSC reads. *(Resource: [Next.js Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations))*' WHERE day_number = 38;
UPDATE rust_challenge_days SET frontend_task = 'State: Master client state separation. Use Zustand to build a robust global UI state (e.g. tracking sidebar open/close, theme) avoiding React Context re-renders. *(Resource: [Zustand docs](https://docs.pmnd.rs/zustand/getting-started/introduction))*' WHERE day_number = 39;
UPDATE rust_challenge_days SET frontend_task = 'State: Master server state management. Use React Query (TanStack Query) to fetch, cache, and mutate data optimistically. *(Resource: [TkDodo''s React Query Blog](https://tkdodo.eu/blog/practical-react-query))*' WHERE day_number = 40;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Study the Compound Component Pattern. Build a highly reusable `<Select>` component using context internally. *(Resource: [Kent C. Dodds Advanced React Patterns](https://kentcdodds.com/))*' WHERE day_number = 41;
UPDATE rust_challenge_days SET frontend_task = 'Review: Audit the React component tree using the React Profiler. Identify and fix one unnecessary re-render.' WHERE day_number = 42;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Learn how to accurately measure Core Web Vitals (CWV). Set up the web-vitals JS library in a Next.js project. *(Resource: [web.dev Vitals](https://web.dev/vitals/))*' WHERE day_number = 43;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Optimize Largest Contentful Paint (LCP). Manually construct a `<link rel="preload">` for a hero image and observe the waterfall change. *(Resource: [Addy Osmani Image Optimization Book](https://www.smashingmagazine.com/printed-books/image-optimization/))*' WHERE day_number = 44;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Optimize Cumulative Layout Shift (CLS). Implement responsive images with correct `srcset` and `sizes` attributes, plus explicit aspect ratios. *(Resource: [MDN Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images))*' WHERE day_number = 45;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Optimize Interaction to Next Paint (INP). Use Chrome DevTools Performance tab to identify a long task and break it up using `setTimeout` or `requestAnimationFrame`. *(Resource: [Optimize INP on web.dev](https://web.dev/optimize-inp/))*' WHERE day_number = 46;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Analyze third-party script impact. Use `next/script` with the `worker` strategy (Partytown) to offload analytics to a Web Worker. *(Resource: [Partytown docs](https://partytown.builder.io/))*' WHERE day_number = 47;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Master the Network Tab. Throttle to Fast 3G, capture a trace, and identify render-blocking CSS or JS. Defer non-critical CSS. *(Resource: [Chrome DevTools Network Analysis](https://developer.chrome.com/docs/devtools/network/))*' WHERE day_number = 48;
UPDATE rust_challenge_days SET frontend_task = 'Performance: Simulate the exact conditions KudiSense''s users will hit — throttle to Slow 3G/Fast 3G, add artificial latency, and verify the app degrades gracefully (loading states, no infinite spinners, no dropped requests silently failing). Mirrors the backend''s load-test day. *(Resource: [Chrome DevTools Network Throttling](https://developer.chrome.com/docs/devtools/network/))*' WHERE day_number = 49;
UPDATE rust_challenge_days SET frontend_task = 'Review: Run a full Lighthouse audit on a heavy page. Aim for 95+ in all categories.' WHERE day_number = 50;
UPDATE rust_challenge_days SET frontend_task = 'Tooling: Set up a strict ESLint and Prettier config from scratch without create-react-app or create-next-app. Understand what every rule does. *(Resource: [ESLint Configuration](https://eslint.org/docs/latest/use/configure/))*' WHERE day_number = 51;
UPDATE rust_challenge_days SET frontend_task = 'Tooling: Configure Vite to bundle a highly optimized React application. Examine the build output using `rollup-plugin-visualizer`. *(Resource: [Vite Docs](https://vitejs.dev/))*' WHERE day_number = 52;
UPDATE rust_challenge_days SET frontend_task = 'Tooling: Write a custom Webpack loader or Vite plugin that transforms custom syntax (e.g. a plugin that converts Markdown to React components). *(Resource: [Vite Plugin API](https://vitejs.dev/guide/api-plugin.html))*' WHERE day_number = 53;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Implement Micro-frontends using Webpack Module Federation. Create a host app that dynamically loads a remote component. *(Resource: [Module Federation Examples](https://github.com/module-federation/module-federation-examples))*' WHERE day_number = 54;
UPDATE rust_challenge_days SET frontend_task = 'Rendering: Study Partial Prerendering (PPR) in Next.js. Combine static shells with dynamic holes in a single route. *(Resource: [Next.js PPR](https://nextjs.org/learn/dashboard-app/partial-prerendering))*' WHERE day_number = 55;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Build a custom SSR (Server-Side Rendering) setup from scratch using Express and `ReactDOMServer.renderToString()`. *(Resource: [React SSR docs](https://react.dev/reference/react-dom/server))*' WHERE day_number = 56;
UPDATE rust_challenge_days SET frontend_task = 'Review: Compare the TTFB (Time to First Byte) and TTI (Time to Interactive) of the custom SSR setup vs the Vite SPA setup.' WHERE day_number = 57;
UPDATE rust_challenge_days SET frontend_task = 'Security: Deep dive into Cross-Site Scripting (XSS). Purposefully build a vulnerable React component using `dangerouslySetInnerHTML`, then fix it using DOMPurify. *(Resource: [Web Security for Developers, Chapter on XSS](https://nostarch.com/websecurity))*' WHERE day_number = 58;
UPDATE rust_challenge_days SET frontend_task = 'Security: Implement a strict Content Security Policy (CSP) header. Configure it to block inline scripts and only allow specific domains for images. *(Resource: [MDN CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP))*' WHERE day_number = 59;
UPDATE rust_challenge_days SET frontend_task = 'Security: Understand CSRF (Cross-Site Request Forgery). Implement SameSite cookie attributes and a CSRF token flow in a Next.js API route. *(Resource: [OWASP CSRF Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html))*' WHERE day_number = 60;
UPDATE rust_challenge_days SET frontend_task = 'Scaling: Build a robust Design System token architecture. Map Figma variables to CSS Custom properties in a structured way (e.g. Tier 1: Core, Tier 2: Semantic, Tier 3: Component). *(Resource: [Nathan Curtis on Design Tokens](https://medium.com/eightshapes-llc/tokens-in-design-systems-25dd82d58431))*' WHERE day_number = 61;
UPDATE rust_challenge_days SET frontend_task = 'Scaling: Implement a custom CLI tool in Node.js that generates boilerplate code for new React components (scaffolding the .tsx, .css, and .test.tsx). *(Resource: [Building Node CLIs](https://developer.okta.com/blog/2019/06/18/command-line-app-with-nodejs))*' WHERE day_number = 62;
UPDATE rust_challenge_days SET frontend_task = 'Scaling: Set up a monorepo using Turborepo. Create a shared `ui` package and a shared `config` package consumed by a Next.js app. *(Resource: [Turborepo Documentation](https://turbo.build/repo))*' WHERE day_number = 63;
UPDATE rust_challenge_days SET frontend_task = 'Review: Run `npm audit` and explore `snyk` to check for dependency vulnerabilities in the monorepo.' WHERE day_number = 64;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Intro to Three.js. Setup a basic scene, camera, and renderer. Render a rotating green cube. *(Resource: [Three.js Journey by Bruno Simon, Intro](https://threejs-journey.com/))*' WHERE day_number = 65;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Explore geometries and materials in Three.js. Create a scene with standard materials and lighting (ambient + point lights). *(Resource: [Three.js Materials Docs](https://threejs.org/docs/#api/en/materials/Material))*' WHERE day_number = 66;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Load a 3D model (.gltf) into the scene. Animate it slowly rotating. *(Resource: [Three.js GLTFLoader](https://threejs.org/docs/#examples/en/loaders/GLTFLoader))*' WHERE day_number = 67;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Transition to React Three Fiber (R3F). Recreate the rotating cube and model loading using R3F declarative syntax. *(Resource: [React Three Fiber Docs](https://docs.pmnd.rs/react-three-fiber/getting-started/introduction))*' WHERE day_number = 68;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Master camera controls. Add `OrbitControls` and implement a smooth camera pan on user scroll. *(Resource: [Drei library](https://github.com/pmndrs/drei))*' WHERE day_number = 69;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Create a particle system in R3F using `InstancedMesh` for high performance rendering of 10,000+ objects. *(Resource: [Yuri Artiukh YouTube on WebGL Particles](https://www.youtube.com/@akella))*' WHERE day_number = 70;
UPDATE rust_challenge_days SET frontend_task = 'Review: Check the FPS of the particle system using `stats.js` (or Drei''s Stats component). Ensure it runs at 60fps.' WHERE day_number = 71;
UPDATE rust_challenge_days SET frontend_task = 'Shaders: Intro to GLSL (OpenGL Shading Language). Write a basic vertex and fragment shader using `ShaderMaterial` in R3F. *(Resource: [The Book of Shaders](https://thebookofshaders.com/))*' WHERE day_number = 72;
UPDATE rust_challenge_days SET frontend_task = 'Shaders: Pass uniforms (time, mouse position) from React to the shader to create a dynamic, animated gradient background. *(Resource: [Three.js Journey: Shaders](https://threejs-journey.com/))*' WHERE day_number = 73;
UPDATE rust_challenge_days SET frontend_task = 'Shaders: Implement a distortion effect on an image texture using UV manipulation in the fragment shader. *(Resource: [Awwards Shader tutorials](https://www.awwwards.com/))*' WHERE day_number = 74;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Post-processing. Add a bloom effect and chromatic aberration to a 3D scene using `@react-three/postprocessing`. *(Resource: [R3F Post-processing](https://docs.pmnd.rs/react-three-fiber/tutorials/post-processing))*' WHERE day_number = 75;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Implement 3D text using Drei''s `<Text3D>` and apply a physical material with environment mapping (HDRI). *(Resource: [PolyHaven HDRIs](https://polyhaven.com/))*' WHERE day_number = 76;
UPDATE rust_challenge_days SET frontend_task = 'WebGL: Create a ''scroll-tied'' 3D experience where a 3D object progresses along a path/curve as the user scrolls down the page. *(Resource: [Bruno Simon Portfolios](https://bruno-simon.com/))*' WHERE day_number = 77;
UPDATE rust_challenge_days SET frontend_task = 'Review: Test the WebGL scene on a mobile device. Adjust the pixel ratio and geometry detail based on device performance.' WHERE day_number = 78;
UPDATE rust_challenge_days SET frontend_task = 'Forms: Build a complex multi-step form using React Hook Form and Zod for strict client-side validation. *(Resource: [React Hook Form + Zod](https://react-hook-form.com/get-started))*' WHERE day_number = 79;
UPDATE rust_challenge_days SET frontend_task = 'A11y: Deep dive into Web Accessibility (WCAG). Manually test the multi-step form using VoiceOver (Mac) or NVDA (Windows) screen readers. *(Resource: [web.dev Accessibility](https://web.dev/accessibility/))*' WHERE day_number = 80;
UPDATE rust_challenge_days SET frontend_task = 'A11y: Master ARIA attributes. Implement a fully accessible custom dropdown component (combobox) following the W3C ARIA APG. *(Resource: [W3C ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/))*' WHERE day_number = 81;
UPDATE rust_challenge_days SET frontend_task = 'Testing: Set up Vitest and React Testing Library. Write unit tests for the complex form validation logic and error state rendering. *(Resource: [React Testing Library Tutorial](https://testing-library.com/docs/react-testing-library/intro/))*' WHERE day_number = 82;
UPDATE rust_challenge_days SET frontend_task = 'Testing: Write integration tests. Mock an API response using MSW (Mock Service Worker) and test the successful form submission flow. *(Resource: [MSW Documentation](https://mswjs.io/))*' WHERE day_number = 83;
UPDATE rust_challenge_days SET frontend_task = 'Testing: Intro to E2E testing with Playwright. Write a script to automate opening the browser, filling the form, and submitting. *(Resource: [Playwright Docs](https://playwright.dev/))*' WHERE day_number = 84;
UPDATE rust_challenge_days SET frontend_task = 'Review: Run an automated Axe core accessibility audit in the Playwright E2E test to catch any regressions.' WHERE day_number = 85;
UPDATE rust_challenge_days SET frontend_task = 'Typography: Study the math behind typographical rhythms. Implement a vertical rhythm using a baseline grid in CSS. *(Resource: [The Elements of Typographic Style for the Web](http://webtypography.net/))*' WHERE day_number = 86;
UPDATE rust_challenge_days SET frontend_task = 'Typography: Learn variable fonts. Implement a variable font (like Inter Variable) and animate its `font-weight` and `font-stretch` axes on hover. *(Resource: [MDN Variable Fonts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide))*' WHERE day_number = 87;
UPDATE rust_challenge_days SET frontend_task = 'Layout: Build a magazine-style editorial layout using CSS Grid areas (`grid-template-areas`) for highly irregular, artistic image placements. *(Resource: [CSS Tricks Grid Areas](https://css-tricks.com/almanac/properties/g/grid-template-areas/))*' WHERE day_number = 88;
UPDATE rust_challenge_days SET frontend_task = 'Layout: Master CSS Shapes. Use `shape-outside` and `clip-path` to make text wrap around a complex polygon image. *(Resource: [MDN CSS Shapes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Shapes))*' WHERE day_number = 89;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Create a custom text reveal animation (e.g. characters masking in one by one) using SplitType.js and GSAP/Motion. *(Resource: [SplitType JS](https://github.com/lukePeavey/SplitType))*' WHERE day_number = 90;
UPDATE rust_challenge_days SET frontend_task = 'Polish: Implement a marquee text effect that runs infinitely and reverses direction on scroll up. *(Resource: [Codrops Marquee Effects](https://tympanus.net/codrops/))*' WHERE day_number = 91;
UPDATE rust_challenge_days SET frontend_task = 'Review: Audit the editorial layout for performance. Ensure custom web fonts aren''t blocking rendering (use `font-display: swap`).' WHERE day_number = 92;
UPDATE rust_challenge_days SET frontend_task = 'DataViz: Intro to D3.js. Build a basic, interactive bar chart rendering directly to an SVG element. *(Resource: [D3 Graph Gallery](https://d3-graph-gallery.com/))*' WHERE day_number = 93;
UPDATE rust_challenge_days SET frontend_task = 'DataViz: Combine D3.js with React. Use D3 for the math/scales and React for rendering the SVG elements to maintain declarative control. *(Resource: [Amelia Wattenberger: React + D3](https://2019.wattenberger.com/blog/react-and-d3))*' WHERE day_number = 94;
UPDATE rust_challenge_days SET frontend_task = 'DataViz: Build an interactive, zoomable scatter plot for thousands of data points. *(Resource: [D3 Zoom API](https://github.com/d3/d3-zoom))*' WHERE day_number = 95;
UPDATE rust_challenge_days SET frontend_task = 'Canvas: Intro to the HTML5 `<canvas>` API. Draw 10,000 animating circles. Notice the performance difference compared to SVG. *(Resource: [MDN Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API))*' WHERE day_number = 96;
UPDATE rust_challenge_days SET frontend_task = 'Canvas: Implement a drawing board/whiteboard using the Canvas API, capturing mouse/touch events. *(Resource: [Fabric.js or plain Canvas tutorials](http://fabricjs.com/))*' WHERE day_number = 97;
UPDATE rust_challenge_days SET frontend_task = 'DataViz: Build a beautiful geographic map visualization (Choropleth map) using D3 geo and TopoJSON. *(Resource: [D3 Geo mapping](https://github.com/d3/d3-geo))*' WHERE day_number = 98;
UPDATE rust_challenge_days SET frontend_task = 'Review: Optimize the D3 React components by memoizing complex path generation calculations using `useMemo`.' WHERE day_number = 99;
UPDATE rust_challenge_days SET frontend_task = 'Privacy-conscious UI: Study how financial apps handle sensitive input (masked fields, no clipboard leakage, no analytics on raw values). Audit a real banking app''s input UX with DevTools open.' WHERE day_number = 100;
UPDATE rust_challenge_days SET frontend_task = 'Privacy-conscious UI: Implement a masked/redactable input component for KudiSense''s financial fields — value never touches `console.log`, network tab, or third-party analytics scripts.' WHERE day_number = 101;
UPDATE rust_challenge_days SET frontend_task = 'Privacy-conscious UI: Since the applicant''s raw data should never leave the device (that''s the whole point of the ZK circuit), audit every network call your dropzone/upload component makes. Confirm the only thing that leaves the browser is what the proving flow actually needs.' WHERE day_number = 102;
UPDATE rust_challenge_days SET frontend_task = 'Privacy-conscious UI: Build a ''clear sensitive state'' utility — wipe form values and any cached raw data from memory/React state the moment a proof is generated or the user navigates away.' WHERE day_number = 103;
UPDATE rust_challenge_days SET frontend_task = 'Privacy-conscious UI: Write the UX copy that explains this to a non-technical user in one sentence: ''your financial details never leave your device.'' Draft 2-3 versions and pick the clearest.' WHERE day_number = 104;
UPDATE rust_challenge_days SET frontend_task = 'Review: Run your ''clear sensitive state'' utility and network-call audit against the checklist your backend track wrote this same week for circuit soundness — two sides of the same trust story.' WHERE day_number = 105;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Design the architecture for the zkML frontend. Setup a Next.js App Router project with Tailwind CSS, Framer Motion, and shadcn/ui. *(Resource: [shadcn/ui Docs](https://ui.shadcn.com/))*' WHERE day_number = 106;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Define the Design System. Configure the `tailwind.config.ts` with custom brand colors, sleek modern fonts (e.g. Geist or Inter), and premium border radiuses. *(Resource: [Vercel Design principles](https://vercel.com/design))*' WHERE day_number = 107;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Build the primary layout shell: a glassmorphism sidebar, a sticky header with a blur backdrop, and a main content area. Since KudiSense targets Nigerian users, add a basic locale toggle (English/Pidgin) to the header now — retrofitting i18n later is expensive, deciding the string-extraction pattern now is cheap. *(Resource: [Tailwind Backdrop Blur](https://tailwindcss.com/docs/backdrop-blur))*' WHERE day_number = 108;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Create an interactive file upload dropzone component for users to upload data (images/csv) for ML inference. Implement drag-and-drop states. *(Resource: [React Dropzone](https://react-dropzone.js.org/))*' WHERE day_number = 109;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Build the ''Proof Generation'' loading state. This is a massive compute task, so create a multi-stage loading skeleton with dynamic progress text (e.g. ''Proving circuit...'', ''Generating witness...''). *(Resource: [Vercel v0 loading state examples](https://v0.dev/))*' WHERE day_number = 110;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Implement the success state: a beautiful dashboard view displaying the ML prediction, the ZK proof hash, and execution time stats. *(Resource: [Tremor React Components](https://tremor.so/))*' WHERE day_number = 111;
UPDATE rust_challenge_days SET frontend_task = 'Review: Test the layout responsiveness on mobile, tablet, and ultra-wide screens. Ensure the glassmorphism degrades gracefully on older browsers.' WHERE day_number = 112;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Integrate the compiled Rust WASM **verifier only** (not the prover — proof generation stays on your Rust proving service, not in the browser) into the Next.js frontend. Configure Turbopack/Webpack to load `.wasm` files. *(Resource: [Next.js WebAssembly](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages))*' WHERE day_number = 113;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Create a Web Worker to run WASM proof *verification* off the main thread so the UI never freezes. Proof *generation* is a network call to your Rust proving service, not worker work — keep the two paths architecturally separate. *(Resource: [MDN Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers))*' WHERE day_number = 114;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Implement the communication bridge between the React components (UI) and the Web Worker (WASM execution) using `postMessage`. *(Resource: [Comlink library for Workers](https://github.com/GoogleChromeLabs/comlink))*' WHERE day_number = 115;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Hook up the file upload component to send data to your Rust proving service (gRPC/REST) for proof *generation*, then verify the returned proof client-side via the WASM verifier in the Worker. Return the boolean result to the UI. *(Resource: [WASM-Bindgen Guide](https://rustwasm.github.io/docs/wasm-bindgen/))*' WHERE day_number = 116;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Add cryptographic flair. When the proof is verifying, render a matrix-like or cryptographic hash visualization using a Canvas element. *(Resource: [Codepen Canvas effects](https://codepen.io/))*' WHERE day_number = 117;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Implement error handling for both failure surfaces: the WASM verifier (catch a Rust panic, display a styled error toast) and the proving-service network call (timeout, 5xx, connection drop — these are now separate and more likely to fail than the verifier). *(Resource: [Sonner Toast component](https://sonner.emilkowal.ski/))*' WHERE day_number = 118;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Build the UI for the reality your backend just stress-tested — a proving queue. Show real queue position / estimated wait when the proving service is under concurrent load, instead of a bare spinner that looks broken after 10 seconds.' WHERE day_number = 119;
UPDATE rust_challenge_days SET frontend_task = 'Review: Benchmark the memory usage of the WASM execution in Chrome DevTools Memory tab to ensure no memory leaks occur across multiple verifications.' WHERE day_number = 120;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Begin the marketing landing page. Scaffold a hero section with massive, bold typography and a clear call to action. *(Resource: [Linear.app design breakdown](https://linear.app/))*' WHERE day_number = 121;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Integrate React Three Fiber into the landing page hero. Render a 3D abstract object (e.g., a wireframe torus knot) that represents the ''zk circuit''. *(Resource: [Three.js TorusKnotGeometry](https://threejs.org/docs/#api/en/geometries/TorusKnotGeometry))*' WHERE day_number = 122;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Make the 3D object interactive. Tie its rotation speed or material color to the user''s mouse position on the screen. *(Resource: [R3F Event system](https://docs.pmnd.rs/react-three-fiber/api/events))*' WHERE day_number = 123;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Build a feature grid section highlighting ''Privacy'', ''Verifiability'', and ''Speed''. Use Motion to stagger animate the grid items in as the user scrolls them into view. *(Resource: [Motion whileInView](https://motion.dev/docs/animation/#scroll-triggered-animations))*' WHERE day_number = 124;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Add a sleek footer and final polish. Implement a dark-mode only theme to maintain the ''hacker/cryptography'' aesthetic consistently. *(Resource: [Tailwind Dark Mode](https://tailwindcss.com/docs/dark-mode))*' WHERE day_number = 125;
UPDATE rust_challenge_days SET frontend_task = 'zkML UI: Optimize the landing page. Ensure the heavy 3D canvas is lazy-loaded (e.g., using `next/dynamic` or `React.lazy`) so the initial page load remains lightning fast. *(Resource: [Next.js Lazy Loading](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading))*' WHERE day_number = 126;
UPDATE rust_challenge_days SET frontend_task = 'Review: Run a final Lighthouse audit on the landing page and the app dashboard. Fix any accessibility or LCP warnings.' WHERE day_number = 127;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Learn WebSockets. Setup a raw WebSocket server in Node.js and a client connection in React. Build a simple live-updating counter. *(Resource: [MDN WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API))*' WHERE day_number = 128;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Migrate from raw WebSockets to Socket.io or tRPC subscriptions for robust real-time communication. *(Resource: [tRPC Subscriptions](https://trpc.io/docs/subscriptions))*' WHERE day_number = 129;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Implement optimistic UI updates. When a user clicks ''Like'' or ''Submit'', update the UI instantly before the server responds, and rollback on error. *(Resource: [React Query Optimistic Updates](https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates))*' WHERE day_number = 130;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Study the Actor Model (XState). Model a complex UI flow (e.g. a checkout process) using a finite state machine instead of boolean flags. *(Resource: [XState Documentation](https://stately.ai/docs/xstate))*' WHERE day_number = 131;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Integrate XState into a React component using `@xstate/react` to manage the complex states robustly. *(Resource: [XState React integration](https://stately.ai/docs/xstate-react))*' WHERE day_number = 132;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Build an offline-first capability using Service Workers and IndexedDB. Cache network requests so the app loads without internet. *(Resource: [Workbox by Google](https://developer.chrome.com/docs/workbox/))*' WHERE day_number = 133;
UPDATE rust_challenge_days SET frontend_task = 'Review: Disconnect your internet and test the PWA/offline capabilities. Ensure fallback UI renders nicely.' WHERE day_number = 134;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Explore the Web Audio API. Build a simple synthesizer keyboard in React that generates oscillator sounds. *(Resource: [MDN Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API))*' WHERE day_number = 135;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Implement an audio visualizer. Capture microphone input via `getUserMedia` and draw the frequency data onto a `<canvas>`. *(Resource: [Web Audio API Visualizations](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API))*' WHERE day_number = 136;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Explore the WebRTC API. Establish a peer-to-peer data channel between two browser windows to send text messages. *(Resource: [WebRTC Architecture](https://webrtc.org/getting-started/peer-connections))*' WHERE day_number = 137;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Explore the File System Access API. Build a text editor in the browser that can read, edit, and save directly to a local `.txt` file on the user''s hard drive. *(Resource: [File System Access API web.dev](https://developer.chrome.com/docs/capabilities/web-apis/file-system-access))*' WHERE day_number = 138;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Explore the Intersection Observer API. Build an infinite scrolling list without using any third-party libraries. *(Resource: [MDN Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API))*' WHERE day_number = 139;
UPDATE rust_challenge_days SET frontend_task = 'Web APIs: Explore the Web Bluetooth or WebUSB API. Understand how the web can communicate with hardware devices. (Conceptual read). *(Resource: [Web Bluetooth web.dev](https://developer.chrome.com/docs/capabilities/bluetooth))*' WHERE day_number = 140;
UPDATE rust_challenge_days SET frontend_task = 'Review: Evaluate the browser support matrix for these advanced APIs using caniuse.com. Write polyfills or fallback UI logic.' WHERE day_number = 141;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Write a comprehensive GitHub Actions workflow for a Next.js app that runs linting, type checking, and unit tests on every PR. *(Resource: [GitHub Actions Docs](https://docs.github.com/en/actions))*' WHERE day_number = 142;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Set up automated visual regression testing using Chromatic or Playwright to catch unintended CSS changes. *(Resource: [Chromatic by Storybook](https://www.chromatic.com/))*' WHERE day_number = 143;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Configure semantic-release to automatically bump version numbers and generate CHANGELOGs based on conventional commits. *(Resource: [Semantic Release](https://semantic-release.gitbook.io/semantic-release/))*' WHERE day_number = 144;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Containerize a Next.js app (standalone output) using Docker. Write a multi-stage Dockerfile optimized for image size. *(Resource: [Next.js Docker deployment](https://nextjs.org/docs/app/building-your-application/deploying#docker-image))*' WHERE day_number = 145;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Implement a staging environment workflow — auto-deploy PRs to preview URLs and run E2E tests against them. Gate one real feature behind a simple flag (a config table or a lightweight service, not necessarily LaunchDarkly) so you can demo progressive rollout — named as senior-level ''plus'' skill in most 2026 postings. *(Resource: [Vercel Preview Deployments](https://vercel.com/docs/deployments/preview-deployments))*' WHERE day_number = 146;
UPDATE rust_challenge_days SET frontend_task = 'DevOps: Setup monitoring and error tracking using Sentry. Intentionally throw an error and analyze the source-mapped stack trace in the Sentry dashboard. *(Resource: [Sentry Next.js setup](https://docs.sentry.io/platforms/javascript/guides/nextjs/))*' WHERE day_number = 147;
UPDATE rust_challenge_days SET frontend_task = 'Review: Review the CI pipeline execution time. Implement caching for `node_modules` and the Next.js build cache to speed it up.' WHERE day_number = 148;
UPDATE rust_challenge_days SET frontend_task = 'Refactoring: Study the ''Render Props'' and ''Custom Hooks'' patterns. Refactor an old, messy component using these patterns to increase reusability. *(Resource: [React Patterns](https://reactpatterns.com/))*' WHERE day_number = 149;
UPDATE rust_challenge_days SET frontend_task = 'Refactoring: Master TypeScript generics, discriminated unions, and the `satisfies` operator together. Build a generic API fetching function that perfectly infers its return type, using a discriminated union for the response shape (success/error) and `satisfies` to keep a config object''s literal types. *(Resource: [Matt Pocock TypeScript tutorials](https://www.totaltypescript.com/))*' WHERE day_number = 150;
UPDATE rust_challenge_days SET frontend_task = 'Refactoring: Study the Dependency Injection pattern in frontend (often via Context or IoC containers). *(Resource: [Inversion of Control in React](https://kentcdodds.com/blog/inversion-of-control))*' WHERE day_number = 151;
UPDATE rust_challenge_days SET frontend_task = 'Architecture: Analyze the concept of ''Clean Architecture'' applied to frontend. Separate the UI components from the business logic (use cases) and infrastructure (API calls). *(Resource: [Clean Architecture on Frontend](https://dev.to/bespoyasov/clean-architecture-on-frontend-4311))*' WHERE day_number = 152;
UPDATE rust_challenge_days SET frontend_task = 'Refactoring: Audit a large codebase (or a large side project) for dead code using `knip` or `ts-prune`. Remove unused exports and dependencies. *(Resource: [Knip documentation](https://knip.dev/))*' WHERE day_number = 153;
UPDATE rust_challenge_days SET frontend_task = 'Refactoring: Analyze bundle size using `next/bundle-analyzer`. Identify a massive library (e.g. lodash or moment) and refactor to use native JS or lighter alternatives. *(Resource: [Next.js Bundle Analyzer](https://www.npmjs.com/package/@next/bundle-analyzer))*' WHERE day_number = 154;
UPDATE rust_challenge_days SET frontend_task = 'Review: Document the architecture rules (e.g. ''Components must not make raw fetch calls'') in a `CONTRIBUTING.md` file.' WHERE day_number = 155;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Dive into the source code of a major open-source UI library (e.g. Radix UI or shadcn/ui). Study how they handle accessibility and polymorphic components (`asChild`). *(Resource: [Radix UI Source Code](https://github.com/radix-ui/primitives))*' WHERE day_number = 156;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Build and publish your own lightweight React component library to npm. Handle the build process with tsup or Rollup. *(Resource: [tsup documentation](https://tsup.egoist.dev/))*' WHERE day_number = 157;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Write comprehensive documentation for your component library using Storybook or Nextra. *(Resource: [Storybook Docs](https://storybook.js.org/))*' WHERE day_number = 158;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Find a ''good first issue'' on a popular frontend repository (e.g. Excalidraw, Vite, or a React library) and investigate the codebase. *(Resource: [GitHub Good First Issues](https://goodfirstissue.dev/))*' WHERE day_number = 159;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Attempt to fix the issue or improve the documentation. Submit a PR. *(Resource: [Open Source Guide](https://opensource.guide/))*' WHERE day_number = 160;
UPDATE rust_challenge_days SET frontend_task = 'Ecosystem: Study the architecture of a complex web app (like Figma or Excalidraw). Read their engineering blogs to understand how they use Canvas/WASM for performance. *(Resource: [Figma Engineering Blog](https://www.figma.com/blog/section/engineering/))*' WHERE day_number = 161;
UPDATE rust_challenge_days SET frontend_task = 'Review: Review the PR feedback or reflect on the design decisions of the major libraries you studied.' WHERE day_number = 162;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Study the Vercel AI SDK. Build a simple chat interface that streams responses from an LLM (OpenAI or Anthropic). *(Resource: [Vercel AI SDK Docs](https://sdk.vercel.ai/docs))*' WHERE day_number = 163;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Implement Generative UI. Have the LLM return structured JSON that dynamically renders React components (e.g. a weather widget) based on the prompt. *(Resource: [Vercel AI SDK Generative UI](https://sdk.vercel.ai/docs/guides/generative-ui))*' WHERE day_number = 164;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Study local-first AI. Run a small model locally in the browser using WebGPU and WebLLM. *(Resource: [WebLLM documentation](https://webllm.mlc.ai/))*' WHERE day_number = 165;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Build a voice-to-text interface using the browser''s native `SpeechRecognition` API. *(Resource: [MDN Speech Recognition](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition))*' WHERE day_number = 166;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Explore spatial computing and WebXR. Build a simple VR scene that can be viewed in a browser headset. *(Resource: [React XR](https://docs.pmnd.rs/react-xr/getting-started/introduction))*' WHERE day_number = 167;
UPDATE rust_challenge_days SET frontend_task = 'Emerging: Study the transition from React to alternative reactive paradigms (SolidJS, Svelte 5 Runes, Vue Vapor). Build a small counter app in SolidJS to understand fine-grained reactivity. *(Resource: [SolidJS Docs](https://www.solidjs.com/))*' WHERE day_number = 168;
UPDATE rust_challenge_days SET frontend_task = 'Review: Evaluate how AI SDKs and local models change the traditional frontend client-server architecture.' WHERE day_number = 169;
UPDATE rust_challenge_days SET frontend_task = 'Portfolio: Apply everything learned to your own portfolio. Audit the typography, spacing, and color harmony. Implement a strict design token system. *(Resource: [Paco Coursey Portfolio](https://paco.me/) for inspiration)*' WHERE day_number = 170;
UPDATE rust_challenge_days SET frontend_task = 'Portfolio: Add a subtle, high-performance WebGL/Three.js hero animation or background effect to the portfolio. *(Resource: [Rauno Freiberg implementations](https://rauno.me/))*' WHERE day_number = 171;
UPDATE rust_challenge_days SET frontend_task = 'Portfolio: Implement flawless view transitions between your project case studies. *(Resource: [View Transitions examples](https://daverupert.com/2023/05/getting-started-view-transitions/))*' WHERE day_number = 172;
UPDATE rust_challenge_days SET frontend_task = 'Portfolio: Write a deep, technical case study for your Rust/zkML project on your blog. Explain the complex systems architecture using clear diagrams. *(Resource: [Excalidraw](https://excalidraw.com/) for diagramming)*' WHERE day_number = 173;
UPDATE rust_challenge_days SET frontend_task = 'Portfolio: Optimize the portfolio to a perfect 100/100/100/100 Lighthouse score. Ensure it loads instantly on 3G. *(Resource: [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci))*' WHERE day_number = 174;
UPDATE rust_challenge_days SET frontend_task = 'Execution: Practice system design for frontend. Mock a staff-level interview question: ''Design the architecture for a real-time collaborative spreadsheet (Google Sheets)''. *(Resource: [Frontend System Design Interview](https://www.frontendinterviewhandbook.com/frontend-system-design))*' WHERE day_number = 175;
UPDATE rust_challenge_days SET frontend_task = 'Review: Have a peer or mentor review your portfolio and your system design architecture.' WHERE day_number = 176;
UPDATE rust_challenge_days SET frontend_task = 'Capstone: Open a PR to the main Rust Challenge repo containing the fully polished, WASM-powered, WebGL-enhanced frontend dashboard for the zkML circuit. *(Resource: Your own hard work!)*' WHERE day_number = 177;
UPDATE rust_challenge_days SET frontend_task = 'Capstone: Review the PR meticulously. Write a staff-level PR description detailing the rendering strategies, state management, and performance optimizations. *(Resource: [How to write a perfect PR](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/))*' WHERE day_number = 178;
UPDATE rust_challenge_days SET frontend_task = 'Capstone: Merge and deploy the capstone project to production. Verify the deployment on live URLs. *(Resource: [Vercel Deployment](https://vercel.com/docs))*' WHERE day_number = 179;
UPDATE rust_challenge_days SET frontend_task = 'Reflection: Write a retrospective on the entire 180-day challenge. Contrast your frontend architecture knowledge on Day 1 vs Day 180. *(Resource: Medium / Hashnode / Dev.to)*' WHERE day_number = 180;
UPDATE rust_challenge_days SET frontend_task = 'Finish: Celebrate the completion of 180 consecutive days of Systems Rust and Staff-level Frontend mastery. Post the results and the live app link on X/Twitter and LinkedIn. *(Resource: You earned it!)*' WHERE day_number = 181;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Find and fix a second good-first-issue in a UI library (shadcn/ui, Radix, or similar). Submit the PR.' WHERE day_number = 182;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Refactor one older component using discriminated unions + `satisfies` — the pattern from earlier this challenge.' WHERE day_number = 183;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Add a real feature-flag-gated experiment to the KudiSense dashboard and write down how you''d measure it.' WHERE day_number = 184;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Finish the English/Pidgin locale toggle on the KudiSense landing page — extract every remaining hardcoded string.' WHERE day_number = 185;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Second mock system-design interview, frontend-specific: ''design a real-time collaborative dashboard for loan officers.''' WHERE day_number = 186;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Speed-run — compare your portfolio case study against 3 real senior-frontend candidate portfolios online. Write down every gap you find.' WHERE day_number = 187;
UPDATE rust_challenge_days SET frontend_task = 'Bonus: Final polish pass on the whole 8-month build. Then actually rest — you earned it.' WHERE day_number = 188;

NOTIFY pgrst, 'reload schema';